# Generated by Django 3.2.4 on 2021-07-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerinfo',
            name='score',
        ),
    ]
