# Generated by Django 3.2.4 on 2021-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
